version: "3.8"

services:
  raspberry:
    image: ghcr.io/nautilus-unipd/raspberry-setup:latest
    privileged: true
    network_mode: "host"
    volumes:
      - /dev:/dev
      - /run/udev:/run/udev
      - ./:$HOME/sensing-rigs-ros2
    group_add:
      - video
    stdin_open: true
    tty: true
    container_name: raspberry_setup

  jetson:
    image: ghcr.io/nautilus-unipd/jetson-nano-setup:latest
    privileged: true
    network_mode: "host"
    volumes:
      - ./:$HOME/sensing-rigs-ros2
    stdin_open: true
    tty: true
    container_name: jetson_setup
